### ISSUE TITLE
Masses and Springs master checklist

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/masses-and-springs#1]
## Design
- [x] **Sim folder and design doc created** (Date: 12/17/2014) 
  - [x] Create sim folder in [PhET Sim Design Folder](https://drive.google.com/drive/folders/0B6CMwxdP0NGYUUhvZnlCUDF0bGc) using phet-docs account
  - [x] Place design doc in the sim folder
- [x] **Legacy sim docs/info gathered**
  - [x] Sim suggestions doc reviewed
  - [x] Unfuddle tickets reviewed
- [x] **Learning goals and standards identified** (Date: 02/25/2016)
- [x] **Design concept complete**  (Date: 01/06/2017)
- [x] **Wireframes complete** (Date: 01/12/2017) 
- [x] **Mockups complete** (Date:01/23/2017) 
  - [x] Mockups checked for colorblind and greyscale
- [ ] **Features for PhET-iO discussion** 
- [x] **Interviews complete** (Date: 01/31/2018) 
  - [x] Results reported to team
  - [x] Notes pasted into design doc
  - [x] Back-up of interviews
- [x] **Lead designer "sign off"** (Date: 05/17/2018) 
  - [x] Performance acceptable
  - [x] Carefully review ?showPointerAreas
  - [x] No new feature requests
- [x] **Pre-publication items** 
  - [x] Main screenshot (2048x1344, PNG, 32-bit color, browser chrome stripped)
  - [x] Auxilary screenshots (up to 3 additional)
  - [x] Accessories (keywords, categories, description, learning goals, related sims, NSDL)
  - [x] Teacher Guide created, uploaded, and added to sim design folder
  - [x] Add an activity
  - [x] Sim primer draft - See #286 
  - [x] Verify credits
  - [x] Re-add MAS to the legacy sim name map on the website, see phetsims/website#659
  - [x] [LoL icons](https://docs.google.com/document/d/1GmLNE31gs8hQYGze3xwmN9k7B6gu7lQ7wJe2phqdH9Y/edit) for each screen created and uploaded to Drive
  - [x] LoL [metadata](https://docs.google.com/spreadsheets/d/1umIAmhn89WN1nzcHKhYJcv-n3Oj6ps1wITc-CjWYytE/edit#gid=562591429) for each screen (description, vocab words, questions for before/after sim use)
- [x] **Post-publication items** 
  - [x] Add the simulation to [responsible_dev.md](https://github.com/phetsims/phet-info/blob/master/sim-info/responsible_dev.md)
  - [x] Add to Edmodo
  - [x] Add to [Gooru](http://gooru.org/PhET/content/resources), remove legacy version (signed in as phethelp)
  - [x] Deliver to [Legends of Learning](https://docs.google.com/spreadsheets/d/1umIAmhn89WN1nzcHKhYJcv-n3Oj6ps1wITc-CjWYytE/edit#gid=0) 
  - [x] Sim primer (create issue, publish ideally within 1 month of live sim) - See #286
  - [ ] Hold postmortem if applicable (Date: //) 

## Implementation
- [x] **Repository created** (Date: 01/19/2016)
  - [x] simula-rasa used to create project skeleton
  - [x] README.md created using `grunt unpublished-readme`
  - [x] Collaborators added (such as QA team, designers, etc)
  - [x] standard GitHub label set applied
  - [x] repository added to chipper/data/ filesr
  - [x] Port existing strings (IF ANY) and commit to the GitHub repo (auto-ported strings from Java and Flash sims can
  be found in babel/autoport). The strings should be deleted from babel/autoport and @jbphet should immediately be asked
  to pull from rosetta to avoid conflicts.
- [x] **Development started** (Date: 01/19/2016)
- [x] **Sim is "feature complete"** (Date: 04/11/2018) 
- [x] **Code review completed** (Date: 05/22/2018) 
- [x] **Published** (Date: 09/19/2018) 
  - [x] README.md updated using `grunt published-readme` (in master and release branch)

## QA
- [x] **Legacy sim tested for bugs**; issues reported in repo
- [x] **Dev testing complete** (Date: 06/06/2018) 
- [x] **First RC published** (Date: 06/08/2018)
  - [x] Test matrices put in [Testing Matrices Folder](https://drive.google.com/drive/folders/0B6CMwxdP0NGYbW9fTGNCODdYVjQ)
- [x] **RC testing completed** (Date: 09/17/2018)

Note: removed testing legacy sim step since this project will pretty much be a rewrite

**Comment by ariel-phet** [comment]
## Design
- [ ] **Sim folder and design doc created** (Date: //) 
  - [ ] Create sim folder in [PhET Sim Design Folder](https://drive.google.com/drive/folders/0B6CMwxdP0NGYUUhvZnlCUDF0bGc) using phet-docs account
  - [ ] Place design doc in the sim folder
- [ ] **Legacy sim docs/info gathered**
  - [ ] Sim suggestions doc reviewed
  - [ ] Unfuddle tickets reviewed
- [ ] **Learning goals and standards identified** (Date: //)
- [ ] **Design concept complete**  (Date: //)
- [ ] **Wireframes complete** (Date: //) 
- [ ] **Mockups complete** (Date: //) 
  - [ ] Mockups checked for colorblind and greyscale
- [ ] **Features for PhET-iO discussion** 
- [ ] **Interviews complete** (Date: //) 
  - [ ] Results reported to team
  - [ ] Notes pasted into design doc
  - [ ] Back-up of interviews
- [ ] **Lead designer "sign off"** (Date: //) 
  - [ ] Performance acceptable
  - [ ] Carefully review ?showPointerAreas
  - [ ] No new feature requests
- [ ] **Pre-publication items** 
  - [ ] Main screenshot (2048x1344, PNG, 32-bit color, browser chrome stripped)
  - [ ] Auxilary screenshots (up to 3 additional)
  - [ ] Accessories (keywords, categories, description, learning goals, related sims, NSDL)
  - [ ] Teacher Guide created, uploaded, and added to sim design folder
  - [ ] Add an activity
  - [ ] Sim primer draft
  - [ ] Verify credits
- [ ] **Post-publication items** 
  - [ ] Add the simulation to [responsible_dev.md](https://github.com/phetsims/phet-info/blob/master/sim-info/responsible_dev.md)
  - [ ] Add to Edmodo
  - [ ] Add to [Gooru](http://gooru.org/PhET/content/resources), remove legacy version (signed in as phethelp)
  - [ ] Sim primer (create issue, publish ideally within 1 month of live sim)
  - [ ] Hold postmortem if applicable (Date: //) 

## Implementation
- [ ] **Repository created** (Date: //)
  - [ ] simula-rasa used to create project skeleton
  - [ ] README.md created using `grunt unpublished-readme`
  - [ ] Collaborators added (such as QA team, designers, etc)
  - [ ] standard GitHub label set applied
  - [ ] repository added to chipper/data/ filesr
  - [ ] Port existing strings (IF ANY) and commit to the GitHub repo (auto-ported strings from Java and Flash sims can
  be found in babel/autoport). The strings should be deleted from babel/autoport and @jbphet should immediately be asked
  to pull from rosetta to avoid conflicts.
- [ ] **Development started** (Date: //)
- [ ] **Sim is "feature complete"** (Date: //) 
- [ ] **Code review completed** (Date: //) 
- [ ] **Published** (Date: //) 
  - [ ] README.md updated using `grunt published-readme` (in master and release branch)

## QA
- [ ] **Legacy sim tested for bugs**; issues reported in repo
- [ ] **Dev testing complete** (Date: //) 
- [ ] **First RC published** (Date: //)
  - [ ] Test matrices put in [Testing Matrices Folder](https://drive.google.com/drive/folders/0B6CMwxdP0NGYbW9fTGNCODdYVjQ)
- [ ] **RC testing completed** (Date: //)

**Comment by arouinfar** [comment]
@Denz1994 @ariel-phet the remaining items are yours.

**Comment by ariel-phet** [comment]
Everything checked, closing
