### ISSUE TITLE
Items for Teacher Tips

### ISSUE THREAD

**Issue by arouinfar** [phetsims/masses-and-springs#174]
For #1 

**Model Simplifications**
- [x] #170 - alternating spring constant causes spring to exceed normal limits 
- [x] #203 - equilibrium position
- [x] Changing a parameter mid-oscillation
- [x] Damping slider controls c, not gamma (gamma = c/2m)
- [x] Negative GPE
- [x] The thickness of the spring is used to indicate the spring constant.
- [x] Constant length vs. spring constant modes
- [x] #218 - Mystery mass densities
- [x] #270 - Period Trace gets thinner as period gets small

**Complex Controls**
- [x] The remove heat button in the Energy Graph will instantaneously remove the thermal energy from the system. If damping is on, the thermal energy will still continue to accumulate.
- [x] When the energy is off-scale, an arrow will appear above the bar in the Energy Graph. To rescale the graph, zoom out until the arrows are no longer visible

**Insights into Student Use**
- [x] It may be helpful to pause the sim when setting up an experiment.
- [x] Students may notice that the displacement vector appears to be asymmetric about the mass equilibrium (greater stretch than compression). This is because the zero point of the displacement vector is at the spring's natural length. Setting the gravity to zero will reveal a symmetric displacement vector about the mass equilibrium. (Related to #221)

**Challenge Prompts**
- [x] Find a way to give a heavier mass a shorter period.

**Comment by arouinfar** [comment]
Since RC testing is imminent, removing `status:on-hold`.

**Comment by arouinfar** [comment]
The tips have been uploaded to drive.
